apiVersion: v1
kind: ConfigMap
metadata:
  name: bao-account-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
  labels:
    app: bao-platform
    env: ${DEPLOY_ENV}
data:
  PGPOOL_HOST: "${PGPOOL_HOST}"
  PGPOOL_DB: "${PGPOOL_DB}"
  PGPOOL_USER: "${PGPOOL_USER}"
  PGPOOL_PORT: "${PGPOOL_PORT}"
  PGPOOL_URL: "${PGPOOL_URL}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  JWT_EXPIRE: "${JWT_EXPIRE}"
  ALLOWED_DOMAINS: "${ALLOWED_DOMAINS}"
  GLOBAL_DOMAIN: "${GLOBAL_DOMAIN}"
  AUTHORIZATION_SERVICE_URL: "${AUTHORIZATION_SERVICE_URL}"
  IMAGE_MAX_SIZE: "${IMAGE_MAX_SIZE}"
  FILE_MAX_SIZE: "${FILE_MAX_SIZE}"
  GRAFANA_OTLP_ENDPOINT: "${GRAFANA_OTLP_ENDPOINT}"
  SERVICE_NAME: "${SERVICE_NAME}"
  DEPLOY_ENV: "${DEPLOY_ENV}"
  GROUP_NAME: "${GROUP_NAME}"
