apiVersion: v1
kind: ConfigMap
metadata:
  name: gau-upload-${DEPLOY_ENV}-config
  namespace: bao-${DEPLOY_ENV}-env
data:
  MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
  MINIO_USE_SSL: "${MINIO_USE_SSL}"
  MINIO_REGION: "${MINIO_REGION}"
  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  TEMP_MINIO_ENDPOINT: "${TEMP_MINIO_ENDPOINT}"
  TEMP_MINIO_REGION: "${TEMP_MINIO_REGION}"
  TEMP_MINIO_USE_SSL: "${TEMP_MINIO_USE_SSL}"
  DEFAULT_CHUNK_SIZE: "${DEFAULT_CHUNK_SIZE}"
  MAX_CHUNK_SIZE: "${MAX_CHUNK_SIZE}"
  TEMP_DIR: "${TEMP_DIR}"
  IMAGE_MAX_SIZE: "${IMAGE_MAX_SIZE}"
  FILE_MAX_SIZE: "${FILE_MAX_SIZE}"
  GRAFANA_OTLP_ENDPOINT: "${GRAFANA_OTLP_ENDPOINT}"
  SERVICE_NAME: "${SERVICE_NAME}"
  DEPLOY_ENV: "${DEPLOY_ENV}"
  GROUP_NAME: "${GROUP_NAME}"
