apiVersion: apps/v1
kind: Deployment
metadata:
  name: gau-upload-http-deployment
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gau-upload-http-service
  template:
    metadata:
      labels:
        app: gau-upload-http-service
    spec:
      containers:
        - name: gau-upload-http-service
          image: iamqbao/gau_upload_service:latest
          envFrom:
            - configMapRef:
                name: gau-upload-${DEPLOY_ENV}-config
            - secretRef:
                name: gau-upload-${DEPLOY_ENV}-secret
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gau-upload-consumer-deployment
  namespace: bao-${DEPLOY_ENV}-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gau-upload-consumer-service
  template:
    metadata:
      labels:
        app: gau-upload-consumer-service
    spec:
      containers:
        - name: gau-upload-consumer-service
          image: iamqbao/gau_upload_service:latest
          command: ["./entrypoint.sh", "consumer"]
          envFrom:
            - configMapRef:
                name: gau-upload-${DEPLOY_ENV}-config
            - secretRef:
                name: gau-upload-${DEPLOY_ENV}-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
