apiVersion: v1
kind: Secret
metadata:
  name: gau-upload-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
type: Opaque
stringData:
  MINIO_ENDPOINT: "${MINIO_API_DOMAIN}"
  MINIO_ACCESS_KEY_ID: "${MINIO_ROOT_USER}"
  MINIO_SECRET_ACCESS_KEY: "${MINIO_ROOT_PASSWORD}"
  MINIO_REGION: "us-east-1"
  MINIO_USE_SSL: "true"
  PRIVATE_KEY: "${PRIVATE_KEY}"
