apiVersion: v1
kind: Secret
metadata:
  name: gau-upload-${DEPLOY_ENV}-secret
  namespace: bao-${DEPLOY_ENV}-env
type: Opaque
stringData:
  MINIO_ACCESS_KEY_ID : "${MINIO_ACCESS_KEY_ID}"
  MINIO_SECRET_ACCESS_KEY  : "${MINIO_SECRET_ACCESS_KEY}"
  PRIVATE_KEY: "${PRIVATE_KEY}"
